version: "3.7"

services:

  mysql:
    image: mysql/mysql-server:8.0.30
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: 172.%.%.%
    volumes:
      - ./volumes/mysql:/var/lib/mysql/
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306
    networks:
      - service_network
    deploy:
      replicas: 1

  redis:
    tty: true
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis-data:/data
    networks:
      - service_network
    deploy:
      replicas: 1

  meilisearch:
    image: getmeili/meilisearch:v1.0
    volumes:
      - ./volumes/meilisearch:/data.ms
    ports:
      - 7700
    environment:
      - MEILI_NO_ANALYTICS
    networks:
      - service_network
    deploy:
      replicas: 1

networks:
  service_network:
    external: true